config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, param: :uuid
  resources :knowledges, param: :uuid
  resources :sessions, only: [:new, :create, :destroy]

  match 'search/', to: 'static_pages#search', via: [:get], as: 'search'
  match 'newnote/', to: 'static_pages#newnote', via: [:get], as: 'newnote'

  match 'items/:uuid/inform', to: 'items#inform', via: [:get], as: 'inform_item'
  resources :items, param: :uuid, only: [:create, :edit, :show, :update] do
    resources :reservations, param: :uuid, only: [:create, :edit, :index, :show]
  end

  resources :matchings, param: :uuid, only: [:create, :edit, :show, :update, :new] do
    resources :matching_conversations, param: :uuid, only: [:create, :edit, :index, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :matching_conversations
  has_many :matchings
  has_many :reservations
  has_many :knowledges
  has_many :items
  def to_param
    uuid
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @item = Item.new
    @user = User.new
  end

  def show
    @item = Item.new
    @items = Item.all if @items == Item
    @items = Item.where(user_id: session[:user_id])

    @my_items = @items.where(user_id: session[:user_id])
                      .where.not(item_type: 'business').order('activity_counter DESC').limit(3)

    @to_matching_conversations = MatchingConversation.where(user_id: session[:user_id])
    # @from_matching_conversations = Matching.matching.where(user_id: session[:user_id])
    @reservations = Reservation.where(user_id: session[:user_id])
  end

  def edit
    @item = Item.new
    @user = User.find(params[:id])
  end

  def update
    @item = Item.new
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Update success'
      redirect_to user_path(session[:user_id])
    else
      flash[:success] = 'Update failed'
      render 'edit'
    end
  end

  def create
    @item = Item.new
    @user = User.new(user_params)
    @user[:uuid] = SecureRandom.uuid
    if @user.save
      redirect_to session[:forwarding_url]
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :pairuser_id, :uuid)
  end
end

app/views/users/edit.html.erb
<div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <!-- エラーメッセージを表示する -->

    <%= f.label "ニックネーム" %>
    <%= f.text_field :name, class: 'form-control'  %>

    <%= f.label "Eメールアドレス" %>
    <%= f.text_field :email, class: 'form-control'  %>

    <%= f.label "ペアユーザーのID" %>
    <%= f.number_field :pairuser_id, class: 'form-control'  %>
    <span id="helpBlock" class="help-block"></span>

    <%= f.label "所属先" %>
    <%= f.text_field :company, class: 'form-control'  %>

    <%= f.label "ユーザータイプ" %>
    <%= f.text_field :user_type, class: 'form-control'  %>

    <%= f.label "パスワード" %>
    <%= f.password_field :password, class: 'form-control'  %>
    <span id="helpBlock" class="help-block"></span>

    <%= f.label "パスワードの再確認" %>
    <%= f.password_field :password_confirmation, class: 'form-control'  %>

    <%= f.submit "アカウント情報の更新", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label "名前" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label "パスワード" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label "パスワードの確認", "パスワードの確認" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "アカウント作成", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container"></div>

<div class="container">
  <h2>あなた「（<%= @current_user.name %>）」さんが予約している装置</h2>
  <ol>
    <% unless @reservations.nil? then %>
    <% @reservations.each do |reservation| %>
    <li class="">
      <span><%= link_to reservation.item.name, item_path(uuid: reservation.item.uuid) %></span>

      <span><%= reservation.start_datetime.strftime("%H時 %M分") %></span>
      <span>から</span>
      <span><%= reservation.end_datetime.strftime("%H時 %M分") %></span>
      <span><%= reservation.name %></span>
      <%= link_to "ical出力", item_reservation_path(item_uuid: reservation.item.uuid, uuid: reservation.uuid, format: :ics) %>
    </li>
    <hr>
    <% end %>
    <% end %>
  </ol>
  <h2>あなた「（<%= @current_user.name %>）」さんが登録した装置</h2>
  <%= render partial: 'shared/items_list',
    locals: {items: @my_items,
    div_tag_name: 'my_items'} %>
  <hr>

</div>

<div class="container">
  <h2>あなた「（<%= @current_user.name %>）」さんがマッチング中の装置</h2>
  <% @to_matching_conversations.each do |matching_conversation| %>
  <div>
    <% if matching_conversation.matching.user_id == @current_user.id %>
    To
    <%= matching_conversation.matching.item.user.company %> 所属 <%= matching_conversation.matching.item.user.name %>
    <% else %>
    From
    <%= matching_conversation.matching.item.user.company %> 所属 <%= matching_conversation.matching.item.user.name %>
    <% end %>
  </div>
  <div><%= link_to matching_conversation.matching.item.name, matching_path(uuid: matching_conversation.matching.uuid ) %></div>
  <div><%= matching_conversation.user.name %></div>
  <div class=""><%= matching_conversation.message %></div>
  <hr>
  <% end %>
</div>