config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, param: :uuid
  resources :knowledges, param: :uuid
  resources :sessions, only: [:new, :create, :destroy]

  match 'search/', to: 'static_pages#search', via: [:get], as: 'search'
  match 'newnote/', to: 'static_pages#newnote', via: [:get], as: 'newnote'

  match 'items/:uuid/inform', to: 'items#inform', via: [:get], as: 'inform_item'
  resources :items, param: :uuid, only: [:create, :edit, :show, :update] do
    resources :reservations, param: :uuid, only: [:create, :edit, :index, :show]
  end

  resources :matchings, param: :uuid, only: [:create, :edit, :show, :update, :new] do
    resources :matching_conversations, param: :uuid, only: [:create, :edit, :index, :show]
  end
end

app/views/shared/_items_list.html.erb
<div class="container items-list-partial <%= div_tag_name %> flexbox-container">
  <% items.each do |item| %>
  <div class="flexbox-item">
    <div class="first-col">
      <%= link_to image_tag(item.webimage_url,
       alt: 'item', class: 'img-rounded img-responsive center-block'),
        item_path(uuid: item.uuid) %>
    </div>
    <div class="second-col">
      <div class="">
        <%= link_to item.name, item_path(uuid: item.uuid) %>
      </div>
      <div class="active-counter">
        装置活発度<strong><%= item.activity_counter %></strong>点
      </div>
      <div class="">
        <span>メーカー</span>
        <span><%= item.manufacture_name %></span>
        <span>型番</span>
        <span><%= item.manufacture_cn %></span>
      </div>
    </div>
    <div class="third-col">
      <div class="prefecture">
        <%= item.prefecture %>
      </div>
      <% if item.item_type == 'innovation' %>
      <div>
        <%= button_to '使用相談', matchings_path(matching: {item_id: item.id, user_id: session[:user_id], match_type: 'innovation'}) %>
      </div>
      <% elsif item.item_type == 'business' %>
      <%= button_to 'デモ依頼', matchings_path(matching: {item_id: item.id, user_id: session[:user_id], match_type: 'business'}) %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_knowledges_list.html.erb
<div class="container knowledges-list-partial <%= div_tag_name %> flexbox-container ">
  <% knowledges.each do |knowledge| %>
  <div class="flexbox-item">
    <div class="">
      <%= link_to image_tag(knowledge.webimage_url,
       alt: 'knowledge', class: 'img-rounded img-responsive center-block'),
        knowledge_path(uuid: knowledge.uuid) %>
    </div>
    <div>
      <%= truncate(knowledge.message, length: 100) %>
    </div>
    <div class="">
      by <%= knowledge.user.company %> 所属の <%= knowledge.user.name %>
    </div>
  </div>
  <% end %>
</div>