config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, param: :uuid
  resources :knowledges, param: :uuid
  resources :sessions, only: [:new, :create, :destroy]

  match 'search/', to: 'static_pages#search', via: [:get], as: 'search'
  match 'newnote/', to: 'static_pages#newnote', via: [:get], as: 'newnote'

  match 'items/:uuid/inform', to: 'items#inform', via: [:get], as: 'inform_item'
  resources :items, param: :uuid, only: [:create, :edit, :show, :update] do
    resources :reservations, param: :uuid, only: [:create, :edit, :index, :show]
  end

  resources :matchings, param: :uuid, only: [:create, :edit, :show, :update, :new] do
    resources :matching_conversations, param: :uuid, only: [:create, :edit, :index, :show]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, length: { maximum: 20 }, presence: true
  validates :message, length: { maximum: 500 }, presense: false
  validates :uuid, length: { maximum: 255 }, uniqueness: true, presence: true

  has_many :reservations
  has_many :matchings
  has_many :knowledges
  belongs_to :user

  def to_param
    uuid
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :inform]

  def create
    @item = Item.new(item_params)
    @item[:uuid] = SecureRandom.uuid
    if @item.save
      flash[:success] = '予約表作成完了！'
      redirect_to item_path(uuid: @item.uuid)
    else
      flash[:success] = 'タイトルを入力してください！'
      render 'static_pages/home'
    end
  end

  def show
    session[:uuid] = params[:uuid]
    session[:id] = @item.id
    date_range = 14
    stdate = Date.today - date_range
    endate = Date.today + date_range
    @former_reservations = date_hashed_reseravations(@item, stdate, Date.today - 1)
    @today_reservations = date_hashed_reseravations(@item, Date.today, Date.today)
    @later_reservations = date_hashed_reseravations(@item, Date.today + 1, endate - 1)
    @reservation = @item.reservations.build
    @knowledges = Knowledge.where(item_id: @item.id).limit(3)
    @current_user = User.find_by(id: session[:user_id])

  end

  def edit
  end

  def update
    if @item.update_attributes(item_params)
      flash[:success] = 'Item情報が更新されました'
      redirect_to inform_item_path(session[:uuid])
    else
      flash[:success] = 'Update failed'
      render 'edit'
    end
  end

  def inform
  end

  def qrcode
    qr = RQRCode::QRCode.new('my string to generate', size: 4, level: :h)
    png = qr.to_img # returns an instance of ChunkyPNG
    png.resize(90, 90).save('really_cool_qr_image.png')
  end

  private

  def set_item
    @item = Item.find_by(uuid: params[:uuid])
  end

  def item_params
    params.require(:item).permit(:name, :message, :manufacture_name, :manufacture_cn)
  end

  def date_hashed_reseravations(item, stdate, endate)
    target_reservations = {}
    # グループ化されたハッシュを用意する
    gouped_reservations = item.reservations.order('start_datetime ASC').group_by do |elem|
      elem.start_datetime.to_date
    end
    (stdate..endate).each do |d|
      target_reservations[d] = if gouped_reservations.key?(d)
                                 gouped_reservations[d]
                               end
    end
    target_reservations
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_calendar.html.erb
<div class="flexbox-container-calendar container">
  <% @today_reservations.each do |key, reservations| %>
  <div class="flexbox-item-calendar">
    <div><%= key.strftime("%d") %></div>
      <% if reservations.nil? then %>
      空
      <% end %>
  </div>
  <% end %>

  <% @later_reservations.each do |key, reservations| %>
  <div class="flexbox-item-calendar">
    <div class=""><%= key.strftime("%d") %></div>
      <% if reservations.nil? then %>
      空
      <% end %>
  </div>
  <% end %>
</div>

app/views/items/_reservations.html.erb
<div class="container">
  <div class="flexbox-container">


    <% @today_reservations.each do |key, reservations| %>
    <div class="flexbox-item">
      <div>
        <h2 class="day-title"><%= key %></h2>
        <button type="button" class="yoyaku general-toggleable-btn btn btn-default pull-right">予約記入</button>
        <div class="toggleable" style="display: none">
          <div class="form-horizontal" role="form">
            <%= form_for [@item, @reservation] do |f| %>
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.time_select :start_datetime, minute_step: 15,
          default: { year: key.year,
            month: key.month,
            day: key.day},
          class: "form-control"
        %>
            <span>から</span>
            <%= f.time_select :end_datetime, minute_step: 15,
          default: { year: key.year,
            month: key.month,
            day: key.day},
          class: "form-control"
        %>
          <% session[:name] = @current_user.name %>
            <%= f.text_field :name, value: session[:name], class: "form-control" %>
            <%= f.submit "予約追加", class: "btn btn-large btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
      <hr>
      <ol>
        <% unless reservations.nil? then %>
        <% reservations.each do |reservation| %>
        <li class="">
          <span><%= reservation.start_datetime.strftime("%H時 %M分") %></span>
          <span>から</span>
          <span><%= reservation.end_datetime.strftime("%H時 %M分") %></span>
          <span><%= reservation.name %></span>
          <%= link_to "ical出力", item_reservation_path(item_uuid: @item.uuid, uuid: reservation.uuid, format: :ics) %>
        </li>
        <% end %>
        <% end %>
      </ol>
    </div>
    <% end %>

    <% @later_reservations.each do |key, reservations| %>
    <div class="flexbox-item">
      <div class="">
        <div class="">
          <h2 class="day-title"><%= key %></h2>
          <button type="button" class="btn btn-default pull-right" data-toggle="collapse" data-target="#collapse<%= key %>">予約記入</button>
        </div>
        <div class="collapse" id="collapse<%= key %>">
          <div class="form-horizontal" role="form">
            <%= form_for [@item, @reservation] do |f| %>
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.time_select :start_datetime, minute_step: 15,
          default: { year: key.year,
            month: key.month,
            day: key.day},
          class: "form-control"
        %>
            <div>
              <span>から</span>
            </div>
            <%= f.time_select :end_datetime, minute_step: 15,
          default: { year: key.year,
            month: key.month,
            day: key.day},
          class: "form-control input-lg"
          %>
            <%= f.text_field :name, value: session[:name], class: "form-control" %>
            <%= f.submit "予約追加", class: "btn btn-large btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
      <hr>
      <ol>
        <% unless reservations.nil? then %>
        <% reservations.each do |reservation| %>
        <li class="">
          <span><%= reservation.start_datetime.strftime("%H時 %M分") %></span>
          <span>から</span>
          <span><%= reservation.end_datetime.strftime("%H時 %M分") %></span>
          <span><%= reservation.name %></span>
          <%= link_to "ical出力", item_reservation_path(item_uuid: @item.uuid, uuid: reservation.uuid, format: :ics) %>
        </li>
        <% end %>
        <% end %>
      </ol>
    </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $(function () {
    $('button.general-toggleable-btn').click(function () {
      $(this).next("div.toggleable").slideToggle();
    });
  });
  $(function () {
    var targetOffset = $('.today_section').offset().top;
    $('html,body').delay(100).animate({
      scrollTop: targetOffset
    }, "slow");
  });
</script>

app/views/items/edit.html.erb
<h1><%= @item.name %></h1>
<div class="container">
  <div class="form-horizontal" role="form">
    <%= form_for [@item] do |f| %>

    <%= f.hidden_field :item_id, value: @item.id %>

    <%= f.label "装置名称" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label "説明" %>
    <%= f.text_area :message, class: "form-control" %>

    <%= f.label "装置メーカー" %>
    <%= f.text_field :manufacture_name, class: "form-control" %>

    <%= f.label "装置型番" %>
    <%= f.text_field :manufacture_cn, class: "form-control" %>
    <%= f.label "装置所有組織" %>
    <%= f.text_field :company, class: "form-control" %>
    <%= f.label "装置設置都道府県" %>
    <%= f.text_field :prefecture, class: "form-control" %>
    <%= f.label "装置設置住所" %>
    <%= f.text_field :address, class: "form-control" %>
    <%= f.label "装置タイプ" %>
    <%= f.text_field :item_type, class: "form-control" %>
    <%= f.submit "変更", class: "btn btn-large btn-primary" %>
    <%= link_to "変更せずに戻る", inform_item_path(uuid: @item.uuid), class: "btn btn-primary" %>
    <% end %>
  </div>

</div>

app/views/items/inform.html.erb
<div class="container">

  <h2>この装置のアクティビティは<%= @item.activity_counter %>です。</h2>
  <hr>
  <table class="table table-striped">
    <tbody>
      <tr>
        <td>装置固有id</td>
        <td><%= @item.id %></td>
      </tr>
      <tr>
        <td>装置名称</td>
        <td><%= @item.name %></td>
      </tr>
      <tr>
        <td>装置説明</td>
        <td><%= simple_format(h(@item.message)) %></td>
      </tr>
      <tr>
        <td>装置会社</td>
        <td><%= @item.manufacture_name %></td>
      </tr>
      <tr>
        <td>装置型番</td>
        <td><%= @item.manufacture_cn %></td>
      </tr>
      <tr>
        <td>所有組織</td>
        <td><%= @item.company %></td>
      </tr>
      <tr>
        <td>設置都道府県</td>
        <td><%= @item.prefecture %></td>
      </tr>
      <tr>
        <td>設置住所</td>
        <td><%= @item.address %></td>
      </tr>
      <tr>
        <td>装置タイプ</td>
        <td><%= @item.item_type %></td>
      </tr>
    </tbody>
  </table>
  <div>
    <%= link_to "装置情報編集", edit_item_path(uuid: @item.uuid), class: "btn btn-primary pull-right" %>
  </div>

</div>

app/views/items/show.html.erb
<div class="container">
  <div class="col-sm-3">
    <%= image_tag(@item.webimage_url,
     alt: 'item', class: 'img-rounded img-responsive center-block') %>
  </div>

  <div class="item-header well-lg col-sm-6">
    <%= auto_link(simple_format(@item.message), html: { target: '_blank' }, link: :urls)   %>
  </div>
  <div class="qrcode col-sm-3" style="display: inline-block;"><%= qrcode_svg(item_path, module_size: 4) %></div>
</div>
<div class="container">
  <hr>
  <%= render partial: 'calendar', locals: { item: @item } %>
  <hr>
  <h2><%= @item.name %>の知見履歴</h2>

  <%= render partial: 'shared/knowledges_list',
              locals: {knowledges: @knowledges,
              div_tag_name: 'knowledges'} %>
  <hr>
  <h2><%= @item.name %>の予約ノート</h2>

  <%= render partial: 'reservations', locals: { item: @item } %>

  <%= link_to "CSV出力", item_reservations_path(item_uuid: @item.uuid, format: :csv), class: "btn btn-primary pull-right" %>

  <%= link_to "ical出力", item_reservations_path(item_uuid: @item.uuid, format: :ics), class: "btn btn-primary pull-right" %>

</div>