config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, param: :uuid
  resources :knowledges, param: :uuid
  resources :sessions, only: [:new, :create, :destroy]

  match 'search/', to: 'static_pages#search', via: [:get], as: 'search'
  match 'newnote/', to: 'static_pages#newnote', via: [:get], as: 'newnote'

  match 'items/:uuid/inform', to: 'items#inform', via: [:get], as: 'inform_item'
  resources :items, param: :uuid, only: [:create, :edit, :show, :update] do
    resources :reservations, param: :uuid, only: [:create, :edit, :index, :show]
  end

  resources :matchings, param: :uuid, only: [:create, :edit, :show, :update, :new] do
    resources :matching_conversations, param: :uuid, only: [:create, :edit, :index, :show]
  end
end

app/views/layouts/_header.html.erb
<header>
  <a href="/" class="navbar-brand">
    <title="">予約ノート</title>
  </a>
  <% if logged_in? %>
  <%= link_to "新規予約ノート作成", newnote_path, method: "get" %>

  <%= link_to '装置検索', search_path, method: "get" %>
  <%= link_to 'マイページ', user_path(uuid: session[:user_uuid]), method: "get" %>
  <%= link_to 'Log out', logout_path, method: "delete" %>
<% else %>
  <%= link_to 'ログインする', login_path %>
  <% end %>
</header>

<% unless @item.blank? || @item.uuid.blank? %>
<div id="secondheader" class="">
  <div class="qrcode" style="display: inline-block;"><%= qrcode_svg(item_path, module_size: 1) %></div>
  <div class="item-header-title">
    <a href="<%= item_path(uuid: @item.uuid) %>" class="">
      <title=""><%= @item.name %></title>
    </a>
  </div>

  <div>
    <%= link_to "装置情報", inform_item_path(uuid: @item.uuid), class: "btn btn-primary pull-right" %>
  </div>
</div>
<% end %>
<script type="text/javascript">
  jQuery(function ($) {
    var nav = $('#secondheader');
    var header = $('header');
    var offset = nav.offset();
    $(window).scroll(function () {
      if ($(window).scrollTop() > offset.top) {
        nav.addClass('fixed');
        header.addClass('header-margin')
      } else {
        nav.removeClass('fixed');
        header.removeClass('header-margin')
      }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">

<html>
  <head>
    <title>Yoyakunote</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
    <!-- ここから -->
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <!-- ここまで追加 -->
    <%= yield %>

  </body>
</html>